# Generated by Django 5.1.3 on 2025-03-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentimage',
            name='uploaded_at',
        ),
    ]
