# Generated by Django 5.1.3 on 2025-03-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_period_1_alter_attendance_period_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_n0',
            new_name='roll_no',
        ),
    ]
